# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser']

    app.markdown_extension:
            class: AppBundle\Twig\MarkdownExtension
            tags:
                - { name: twig.extension }
            #arguments: ['@app.markdown_transformer']
            autowire: true